# Generated by Django 3.2.2 on 2021-05-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='post Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='thumbnail',
            field=models.ImageField(upload_to='cphotos/photos'),
        ),
    ]
